import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Register new account | Wincorn Medical Solution",
  description: "Generated by create next app",
};

export default function CategoriesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
