name: CI/CD Pipeline for wincornmedical

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/wincornmedical:latest .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/wincornmedical:latest ${{ secrets.DOCKER_HUB_USERNAME }}/wincornmedical:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wincornmedical:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wincornmedical:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Replace the Docker image in docker-compose.production.yaml
        run: |
          sed -i 's|${DOCKER_IMAGE}|${{ secrets.DOCKER_HUB_USERNAME }}/wincornmedical:${{ github.sha }}|g' docker-compose.production.yaml

      - name: Transfer docker-compose.production.yaml as docker-compose.yaml
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}
          SUDO_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no docker-compose.production.yaml $USERNAME@$HOST:/tmp/docker-compose.yaml
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "echo '$SUDO_PASSWORD' | sudo -S mkdir -p /var/www/html/wincornmedical && echo '$SUDO_PASSWORD' | sudo -S mv /tmp/docker-compose.yaml /var/www/html/wincornmedical/docker-compose.yaml"

      - name: Transfer .env
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}
          SUDO_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no .env $USERNAME@$HOST:/tmp/.env
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "echo '$SUDO_PASSWORD' | sudo -S mv /tmp/.env /var/www/html/wincornmedical/.env"

      - name: Deploy application
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PASSWORD: ${{ secrets.VPS_PASSWORD }}
          SUDO_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          cd /var/www/html/wincornmedical &&
          echo '$SUDO_PASSWORD' | sudo -S docker-compose pull &&
          echo '$SUDO_PASSWORD' | sudo -S docker-compose down &&
          echo '$SUDO_PASSWORD' | sudo -S docker-compose up -d --force-recreate"
